-- 1. Create locations table
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create item_locations table
CREATE TABLE IF NOT EXISTS item_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT REFERENCES items(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  quantity NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(item_id, location_id)
);

-- 3. Insert default 'Main Location' if it doesn't exist
INSERT INTO locations (name, is_default)
VALUES ('Main Location', TRUE)
ON CONFLICT (name) DO NOTHING;

-- 4. Migrate existing stock to Main Location
-- This grabs the ID of 'Main Location' and inserts records for all items
DO $$
DECLARE
  main_loc_id BIGINT;
BEGIN
  SELECT id INTO main_loc_id FROM locations WHERE name = 'Main Location' LIMIT 1;

  INSERT INTO item_locations (item_id, location_id, quantity)
  SELECT id, main_loc_id, stock_quantity
  FROM items
  ON CONFLICT (item_id, location_id) 
  DO UPDATE SET quantity = EXCLUDED.quantity;
END $$;
