-- Add role column to profiles table
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS role text DEFAULT 'staff' CHECK (role IN ('staff', 'manager', 'admin'));

-- Create item_dates table
CREATE TABLE IF NOT EXISTS item_dates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint REFERENCES items(id) ON DELETE CASCADE,
    label text NOT NULL,
    target_date date NOT NULL,
    notify_manager boolean DEFAULT true,
    reminder_sent boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Create index for faster queries on target_date (for reminders)
CREATE INDEX IF NOT EXISTS idx_item_dates_target_date ON item_dates(target_date);
CREATE INDEX IF NOT EXISTS idx_item_dates_reminder_sent ON item_dates(reminder_sent);
