-- 1. Fix Role Constraint to allow capitalized roles
-- First, drop the existing constraint if we can find its name, or just alter the column type to text and re-add constraint
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE profiles 
ADD CONSTRAINT profiles_role_check 
CHECK (role IN ('staff', 'manager', 'admin', 'Staff', 'Manager', 'Admin'));

-- 2. Create general_dates table
CREATE TABLE IF NOT EXISTS general_dates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL,
    target_date date NOT NULL,
    notify_manager boolean DEFAULT true,
    reminder_sent boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_general_dates_target_date ON general_dates(target_date);
CREATE INDEX IF NOT EXISTS idx_general_dates_reminder_sent ON general_dates(reminder_sent);
